services:
  - type: web
    name: hamj-top-pay
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hamj-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hamj-redis
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@hamjtoppay.com
      - key: ADMIN_PASSWORD
        value: admin123

  - type: redis
    name: hamj-redis
    ipAllowList: [] # only allow internal connections
    plan: free

databases:
  - name: hamj-db
    databaseName: hamj_top_pay
    user: hamj_user
    plan: free
